Fix composition types
jantimon/next-yak pull request #104
Opened 2024-06-24 10:47 UTC by Mad-Kat

Fixes #72 

Use `NoInfer<T>` in order to be explicit for the tagged template literal types and not inferring them from the functions that are used for dynamic props or child components.

Added bonus: The destructuring of the props in the tagged template literal gives you now type hints, as TypeScript doesn't want to infer it dynamically and the type is known when you start with the literal.

2024-06-24 11:07 UTC, jantimon commented
Would this be valid in styled components?

```tsx
  const Child = styled.div<{ $child: boolean }>`
      ${({ $child }) =>
        $child &&
        css`
          color: red;
        `}
    `;

    const Parent = styled.div`
      ${Child} {
        color: blue;
      }
      color: ${({ $colorMe }) => $colorMe ? `blue` : `red`};
    `;
```

It seems to fail for us (see broken pipeline error):
`Property '$colorMe' does not exist on type 'ClassAttributes<HTMLDivElement> & HTMLAttributes<HTMLDivElement> & { $child: boolean; } & { theme: YakTheme; }'.ts(2339)`

2024-06-24 11:08 UTC, jantimon requested changes
Would this be valid in styled components?

```tsx
  const Child = styled.div<{ $child: boolean }>`
      ${({ $child }) =>
        $child &&
        css`
          color: red;
        `}
    `;

    const Parent = styled.div`
      ${Child} {
        color: blue;
      }
      color: ${({ $colorMe }) => $colorMe ? `blue` : `red`};
    `;
```

It seems to fail for us (see broken pipeline error):
`Property '$colorMe' does not exist on type 'ClassAttributes<HTMLDivElement> & HTMLAttributes<HTMLDivElement> & { $child: boolean; } & { theme: YakTheme; }'.ts(2339)`

2024-06-24 11:15 UTC, jantimon commented
Just checked and styled-component seems to behave the same:
https://stackblitz.com/edit/vitejs-vite-vttcyb?file=src%2Fmain.tsx,src%2FApp.tsx&terminal=dev

I adjusted the tests and added @ts-expect-error

2024-06-24 11:17 UTC, merged

2024-06-25 06:15 UTC, Mad-Kat commented
Yeah I think you need to write it like this:

```
const Parent = styled.div<{ $colorMe: boolean }>`
      ${Child} {
        color: blue;
      }
      color: ${({ $colorMe }) => $colorMe ? `blue` : `red`};
    `;
```

you have to add the type parameter in order to say that `$colorMe` exists. It doesn't automatically infer it from the functions you provide.

2024-06-25 06:16 UTC, jantimon commented
released as 0.2.2