Try to extract css units in css expressions
jantimon/next-yak pull request #64
Opened 2024-02-07 16:59 UTC by rvetere

fixes #54

2024-02-07 17:21 UTC, Mad-Kat requested changes
Thank you for the PR :)
It goes in a good direction, but I think it's still missing some crucial cases that can happen.

2024-02-07 17:21 UTC, Mad-Kat commented on packages/next-yak/loaders/babel-yak-plugin.cjs
> +              quasis[i + 1] && extractCssUnit(quasis[i + 1].value.raw);
What happens if you have more than one unit in your quasi?
e.g.
```
margin: ${x}rem;
padding: 10px;
```

In this case your quasi would be `rem;\r\npadding: 10px;` and your detection wouldn't work, or would it?

2024-02-07 17:21 UTC, Mad-Kat commented on packages/next-yak/loaders/__tests__/tsloader.test.ts
Thank you for the test. I would love to have some more tests, that cover more cases that can happen

2024-02-07 17:21 UTC, Mad-Kat commented on packages/next-yak/loaders/babel-yak-plugin.cjs
> +              expression.value = expression.value + ` + "${cssUnit}"`;
What do you mean by that? Do you mean that we should know the compile time value at this point?

2024-02-07 17:25 UTC, rvetere commented on packages/next-yak/loaders/babel-yak-plugin.cjs
> +              quasis[i + 1] && extractCssUnit(quasis[i + 1].value.raw);
oooh good catch, i didn't thought about that case yet ^^

2024-02-07 18:26 UTC, rvetere commented on packages/next-yak/loaders/babel-yak-plugin.cjs
> +              quasis[i + 1] && extractCssUnit(quasis[i + 1].value.raw);
should be more bulletproof now by splitting on ";"

2024-02-08 14:04 UTC, jantimon commented
please add tests for those cases:

```ts
const case1 = css`${4}px`

const case2 = css`${({$indent}) => $indent > 4 ? 10 : $indent}px`

const case3 = css`${({$indent}) => {
  if ($indent > 4) return 10;
  return $indent
}}px`
```

One idea if we cant fix case3 (or even more complicated cases):

```ts
({$indent}) => {
  if ($indent > 4) return 10;
  return $indent
}
```

for properties an expression is a function which returns a number or string

we could add a helper which executes this function and appends the unit afterwards e.g.:

```tsc
const __yakAppendUnit = ( baseFunction, unit ) => {
   // run a new function which accepts the same args as `baseFunction`:
   return (...args) => {
      // execute the baseFunction
      const baseFunctionResult = baseFunction(...args);
      // add the unit
      return baseFunctionResult + unit
  }
}
```

that way we could solve even the most complicated cases:

```ts
const case3 = css`${__yakAppendUnit(

({$indent}) => {
  if ($indent > 4) return 10;
  return $indent
}

, "px")}`
```

2024-02-13 11:22 UTC, jantimon requested changes

2024-02-14 08:01 UTC, rvetere commented on packages/next-yak/loaders/babel-yak-plugin.cjs
> +            const isAnimationExpression =
solved it in a new way, we need to further discuss this

2024-02-14 08:40 UTC, rvetere commented on packages/next-yak/loaders/lib/handleCssUnitInExpression.cjs
> +  const [firstCssString] = quasi.trim().split(";");
let's discuss this shortly

2024-02-14 08:40 UTC, rvetere commented on packages/next-yak/loaders/lib/handleCssUnitInExpression.cjs
> +        expression,
re-written

2024-02-14 08:40 UTC, rvetere commented on packages/next-yak/loaders/lib/handleCssUnitInExpression.cjs
> +    const cssUnit = nextQuasi && extractCssUnit(nextQuasi.value.raw);
done

2024-02-14 09:36 UTC, jantimon requested changes
I might be wrong but I don't think that `forbiddenValues` is needed and would be a big maintenance effort.

But maybe I don't understand it entirely - why would we need this?

Wouldn't it be the same problem for font, background, ...?

2024-02-14 09:36 UTC, jantimon commented on packages/next-yak/loaders/__tests__/tsloader.test.ts
> +  it("should detect expressions with units in complex arrow functions and wrap them with __yak_unitPostFix helper", async () => {
can't see any `__yak_unitPostFix`

2024-02-14 09:36 UTC, jantimon commented on packages/next-yak/loaders/babel-yak-plugin.cjs
> +          // Initialize a state flag to track whether the import should be added
?

2024-02-14 09:36 UTC, jantimon commented on packages/next-yak/loaders/babel-yak-plugin.cjs
> +          // Check the flag and add the import at the end of processing
```suggestion
          // After processing the file add imports for all injected runtime helpers
```

2024-02-14 09:36 UTC, jantimon commented on packages/next-yak/loaders/babel-yak-plugin.cjs
> +            const transformedExpression = cssUnit
very readable 👍👍
even better than my idea

one really tiny thing - could you please find a more concrete name than "handle"?

2024-02-14 09:36 UTC, jantimon commented on packages/next-yak/loaders/cssloader.cjs
> +          code = code.replace(/^([a-z]+|%)/, "");
could we explain why we need to remove the css unit?

sth like:

```suggestion
          // a quasi might start with a css unit e.g. css`margin: ${value}px 0;`
          // the css unit will be part of the typescript runtime code and must
          // must be removed from the css code as `var(--foo)px` would be invalid css
          code = code.replace(/^([a-z]+|%)/, "");
```

2024-02-14 09:36 UTC, jantimon commented on packages/next-yak/loaders/lib/__tests__/extractCssUnit.test.ts
> +      " ease-out 1s infinite reverse both paused slidein;\n", // => ease-out
this is wrong - ease-out is not a css unit but the next value

2024-02-14 09:36 UTC, jantimon commented on packages/next-yak/loaders/lib/__tests__/extractCssUnit.test.ts
> +        "ease",
```suggestion
        null,
```

2024-02-14 09:36 UTC, jantimon commented on packages/next-yak/loaders/lib/__tests__/extractCssUnit.test.ts
> +      return extractCSSUnit(cssString);
maybe this could improve the readability of the result as we always see input -> output

```suggestion
      return { code: cssString, unit: extractCSSUnit(cssString) };
```

2024-02-14 09:36 UTC, jantimon commented on packages/next-yak/loaders/lib/extractCssUnit.cjs
> +  const nextQuasi = quasi.includes(";") ? quasi.split(";")[0] : quasi;
why do we need this line?

2024-02-14 09:36 UTC, jantimon commented on packages/next-yak/loaders/lib/extractCssUnit.cjs
> + * Extracts the css unit from a css string and checks if it is a valid CSS unit
```suggestion
 * Extracts the css unit from the start of a css quasi e.g.:
 *
 * ```js
 *   // in the AST this code would have two quasis: "margin: " and "px 0 14px;"
 *   css`margin: ${size}px 0 14rem;` 
 * ```
```

2024-02-14 09:36 UTC, jantimon commented on packages/next-yak/loaders/lib/extractCssUnit.cjs
> + * example:
maybe skip these examples

2024-02-14 09:36 UTC, jantimon commented on packages/next-yak/loaders/lib/handleCssUnitInExpression.cjs
> +const CSS_ANIMATION_UNITS = [
please remove

2024-02-14 09:36 UTC, jantimon commented on packages/next-yak/loaders/lib/handleCssUnitInExpression.cjs
> +const FORBIDDEEN_UNITS = [...CSS_ANIMATION_UNITS];
please remove

2024-02-14 09:36 UTC, jantimon commented on packages/next-yak/loaders/lib/handleCssUnitInExpression.cjs
> +    if (!FORBIDDEEN_UNITS.includes(cssUnit)) {
why forbidden units?

2024-02-14 09:36 UTC, jantimon commented on packages/next-yak/loaders/lib/handleCssUnitInExpression.cjs
> +         * Functions that are not directly returing a value are wrapped with a helper function:
I guess this comment belongs to the else case - could you please move it and also add a comment here for the __yak_unitPostFix case?

2024-02-14 09:58 UTC, rvetere commented on packages/next-yak/loaders/lib/handleCssUnitInExpression.cjs
> +         * Functions that are not directly returing a value are wrapped with a helper function:
nooow it's solved much better

2024-02-14 09:58 UTC, rvetere commented on packages/next-yak/loaders/lib/handleCssUnitInExpression.cjs
> +    if (!FORBIDDEEN_UNITS.includes(cssUnit)) {
deleted again

2024-02-14 09:58 UTC, rvetere commented on packages/next-yak/loaders/lib/handleCssUnitInExpression.cjs
> +const FORBIDDEEN_UNITS = [...CSS_ANIMATION_UNITS];
done

2024-02-14 09:59 UTC, rvetere commented on packages/next-yak/loaders/lib/handleCssUnitInExpression.cjs
> +const CSS_ANIMATION_UNITS = [
done

2024-02-14 10:01 UTC, rvetere commented on packages/next-yak/loaders/__tests__/tsloader.test.ts
> +  it("should detect expressions with units in complex arrow functions and wrap them with __yak_unitPostFix helper", async () => {
solved

2024-02-14 10:02 UTC, rvetere commented on packages/next-yak/loaders/babel-yak-plugin.cjs
> +          // Initialize a state flag to track whether the import should be added
done

2024-02-14 10:02 UTC, rvetere commented on packages/next-yak/loaders/babel-yak-plugin.cjs
> +            const transformedExpression = cssUnit
yes will think about... :) suggestions? :)

2024-02-14 10:03 UTC, rvetere commented on packages/next-yak/loaders/lib/extractCssUnit.cjs
> +  const nextQuasi = quasi.includes(";") ? quasi.split(";")[0] : quasi;
not there anymore

2024-02-14 10:04 UTC, jantimon commented on packages/next-yak/loaders/babel-yak-plugin.cjs
> +            const transformedExpression = cssUnit
not really maybe @Mad-Kat ?
if we can't find a better one `handle` is good enough

2024-02-14 10:06 UTC, rvetere commented on packages/next-yak/loaders/babel-yak-plugin.cjs
> +            const transformedExpression = cssUnit
"appendCssUnitsInExpression" evtl.?
"supportCssUnitInExpression"

2024-02-14 10:18 UTC, Mad-Kat approved these changes

2024-02-14 10:18 UTC, Mad-Kat commented on packages/next-yak/loaders/lib/handleCssUnitInExpression.cjs
> +    }
Maybe it makes sense to move this statement outside of the `if` above. This would reduce nesting and makes it clearer that this is a separate case from the others

2024-02-14 10:18 UTC, Mad-Kat commented on packages/next-yak/loaders/babel-yak-plugin.cjs
> +            const transformedExpression = cssUnit
`replace` or `add`? But `append` would also work

2024-02-14 10:19 UTC, Mad-Kat commented on packages/next-yak/loaders/babel-yak-plugin.cjs
> +            const transformedExpression = cssUnit
`replace` or `add`? But `append` would also work

2024-02-14 10:42 UTC, jantimon commented on packages/next-yak/loaders/babel-yak-plugin.cjs
> +            const transformedExpression = cssUnit
maybe `moveCssUnitIntoExpression`?

2024-02-14 10:44 UTC, jantimon commented on packages/next-yak/loaders/babel-yak-plugin.cjs
> +            const transformedExpression = cssUnit
I like `append` most as it means add it to the end

`appendCssUnitToExpressionValue` ? 🤣

2024-02-14 10:47 UTC, jantimon commented on packages/next-yak/loaders/lib/extractCssUnit.cjs
> +  const match = quasi.match(/\s|([a-z%]+)(?=;|\s|\))/);
We don't want to find any css unit but only leading css units as only leading units would follow after an expression.

e.g.:
```js
const extractLeadingCssUnit = (code) => code.match(/^([a-z]+|%)/i)?.[0]
```

Maybe now that it is really only `.match(/^([a-z]+|%)/i)?.[0]` we can keep it in the main file and don't have to create a dedicated file for a simple regexp

2024-02-14 10:49 UTC, jantimon requested changes

2024-02-14 10:49 UTC, jantimon commented on packages/next-yak/loaders/cssloader.cjs
> +          code = code.replace(/^([a-z]+|%)/, "");
`PX` is valid css - I hope no one writes code like this but still we should add support and keep the regexp equal to the ts-loader

```suggestion
          code = code.replace(/^([a-z]+|%)/i, "");
```

2024-02-14 10:51 UTC, jantimon commented on packages/next-yak/loaders/lib/handleCssUnitInExpression.cjs
> +  return expression;
the comment looks wrong to me - which cases would come here - should we throw an error?

2024-02-14 15:22 UTC, rvetere commented on packages/next-yak/loaders/babel-yak-plugin.cjs
> +            const transformedExpression = cssUnit
Ich übernehm mal `appendCssUnitToExpressionValue`, gefällt mir :)

2024-02-14 15:23 UTC, rvetere commented on packages/next-yak/loaders/lib/handleCssUnitInExpression.cjs
> +    }
i agree - i buildet it like this because first i was hoping i could re-use the "else" case of the arrow-function handling for all other cases, but this is not true anymore... so you're change makes totally sense!

2024-02-14 15:56 UTC, jantimon approved these changes

2024-02-14 15:57 UTC, merged