Add :global() to inline css classes automatically
jantimon/next-yak pull request #68
Opened 2024-02-14 09:06 UTC by rvetere

2024-02-14 10:30 UTC, Mad-Kat reviewed
Thank you for the PR :)

Could you add some more tests for the following cases:
```jsx
import { styled, keyframes } from "next-yak";

const Link = styled.a\`
  color: palevioletred;
\`

const Icon = styled.svg\`
  \${Link} & {
    color: red;
  }
\`
```

```jsx
import { styled, keyframes } from "next-yak";

const Component = styled.a\`
  .any-class:hover {
    color: red;
  }
\`;
```

```jsx
import { styled, keyframes } from "next-yak";

const Component = styled.a\`
  :where(.any-class) {
    color: red;
  }
\`;
```

2024-02-14 10:30 UTC, Mad-Kat commented on packages/next-yak/loaders/__tests__/cssloader.test.ts
> +       :global(dark-mode) {
this should be `:global(.dark-mode)`

2024-02-14 10:34 UTC, Mad-Kat requested changes
I think it doesn't handle all cases yet, but feel free to change and rerequest a review once my points are fixed

2024-07-23 05:55 UTC, jantimon commented
I'll close this for now because of the conflicts - feel free to reopen :)

2024-07-23 05:55 UTC, closed without merging